name: SiegeBattle
version: ${project.version}
main: mae.siegebattle.SiegeBattle

commands:
  battle:
    usage: /<command>
    description: test app
    permission-message: You don't have <permission>

  user:
      usage: /<command>
      description: test app
      permission-message: You don't have <permission>

  kit:
        usage: /<command>
        description: test app
        permission-message: You don't have <permission>